POST http://localhost:3002/api/user/create
Content-Type: application/json

{
    "phone": "235678567",
    "name": "bdbxcvb",
    "password": "1234567"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
    "phone": "123456",
    "password": "1234567"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
    "phone": "012345678",
    "password": "1234567"
}

###
GET http://localhost:3002/api/user/list

### 
POST http://localhost:3002/api/conversion/create
Content-Type: application/json

{
    "members": ["cvbccc", "svdsdv"],
    "type": "private"
}

###
GET http://localhost:3002/api/conversion/list/abc

###
POST http://localhost:3002/api/message/create
Content-Type: application/json

{
    "message": "ahihi"
}